server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: ON_PARAM
    include-exception: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

com:
  pablo:
    scheduling:
      enabled: true
    security:
      enabled: true
    caching:
      enabled: true
    async:
      enabled: true
    auditing:
      enabled: true
    trace:
      enabled: true

management:
  info:
    java:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - mappings
          - beans
          - startup
          - env
          - scheduledtasks
          - caches
          - metrics
          - info