spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: example
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

com:
  pablo:
    scheduling:
      enabled: true
    security:
      enabled: true
    caching:
      enabled: true

management:
  info:
    java:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - mappings
          - beans
          - startup
          - env
          - scheduledtasks
          - caches
          - metrics
          - info